### ISSUE TITLE
测试了一下，初始加载速度似乎有点慢

### ISSUE THREAD

**Issue by cuiliang** [2300070/ezpinyin#2]
AMD 5900x，大概要2秒左右。
另外中英文混合内容，英文会变成全角字符，不知道是否是这样设计的。如果希望对中英文混合内容做匹配，变成全角就没法处理了。

**Comment by AbotMe** [comment]
初始启动时需要加载字典与词典数据，需要消耗一点时间。对于非汉字字符，默认返回原字符本身，只是后面与汉字一样附加了一个分隔符，所以看起来好像是全角一样，实际上并不是。
